### PR TITLE
Test push notification function

### PR DESCRIPTION
**Pull request by Keido0208**

### CODE REVIEW

**Comment by vineam03** [comment]
may cause merge conflict with WB TC3 (TC1001 on tracker) and TC4 (TC1002)?

**Comment by Kenneth-W-Chen** [comment]
Why is there a `storage.dart` in the test directory?

**Comment by Keido0208** [comment]
> Why is there a `storage.dart` in the test directory?

Because I want to know how it looks like when it is added to the "storage.dart" main branch. If it could start conflict I can simply change file's name

**Comment by Kenneth-W-Chen** [comment]
> Because I want to know how it looks like when it is added to the "storage.dart" main branch. If it could start conflict I can simply change file's name

Why didn't you use the one that's in the `lib` directory? Also, why'd you remake some of the functions from `storage.dart` in `storage_test.dart`?

**Comment by Keido0208** [comment]
Just fix from comments

**Comment by vineam03** [comment]
Save notification functionality we might need to use this later on, however due to incompatibility issues with current main branch this PR will be closed.

**Pull request closed without merging**
